# Generated by Django 5.0.1 on 2024-07-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friend_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
